# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.8

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/daniel/Área de Trabalho/postwar"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/daniel/Área de Trabalho/postwar"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/local/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package

.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/local/bin/cpack --config ./CPackSourceConfig.cmake /home/daniel/Área\ de\ Trabalho/postwar/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source

.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/daniel/Área de Trabalho/postwar/CMakeFiles" "/home/daniel/Área de Trabalho/postwar/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/daniel/Área de Trabalho/postwar/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named postwar

# Build rule for target.
postwar: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 postwar
.PHONY : postwar

# fast build rule for target.
postwar/fast:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/build
.PHONY : postwar/fast

source/GameFeatures/Creditos/creditos.o: source/GameFeatures/Creditos/creditos.cpp.o

.PHONY : source/GameFeatures/Creditos/creditos.o

# target to build an object file
source/GameFeatures/Creditos/creditos.cpp.o:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/GameFeatures/Creditos/creditos.cpp.o
.PHONY : source/GameFeatures/Creditos/creditos.cpp.o

source/GameFeatures/Creditos/creditos.i: source/GameFeatures/Creditos/creditos.cpp.i

.PHONY : source/GameFeatures/Creditos/creditos.i

# target to preprocess a source file
source/GameFeatures/Creditos/creditos.cpp.i:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/GameFeatures/Creditos/creditos.cpp.i
.PHONY : source/GameFeatures/Creditos/creditos.cpp.i

source/GameFeatures/Creditos/creditos.s: source/GameFeatures/Creditos/creditos.cpp.s

.PHONY : source/GameFeatures/Creditos/creditos.s

# target to generate assembly for a file
source/GameFeatures/Creditos/creditos.cpp.s:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/GameFeatures/Creditos/creditos.cpp.s
.PHONY : source/GameFeatures/Creditos/creditos.cpp.s

source/GameFeatures/Jogar/Fase1/carrega_unidades.o: source/GameFeatures/Jogar/Fase1/carrega_unidades.cpp.o

.PHONY : source/GameFeatures/Jogar/Fase1/carrega_unidades.o

# target to build an object file
source/GameFeatures/Jogar/Fase1/carrega_unidades.cpp.o:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/GameFeatures/Jogar/Fase1/carrega_unidades.cpp.o
.PHONY : source/GameFeatures/Jogar/Fase1/carrega_unidades.cpp.o

source/GameFeatures/Jogar/Fase1/carrega_unidades.i: source/GameFeatures/Jogar/Fase1/carrega_unidades.cpp.i

.PHONY : source/GameFeatures/Jogar/Fase1/carrega_unidades.i

# target to preprocess a source file
source/GameFeatures/Jogar/Fase1/carrega_unidades.cpp.i:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/GameFeatures/Jogar/Fase1/carrega_unidades.cpp.i
.PHONY : source/GameFeatures/Jogar/Fase1/carrega_unidades.cpp.i

source/GameFeatures/Jogar/Fase1/carrega_unidades.s: source/GameFeatures/Jogar/Fase1/carrega_unidades.cpp.s

.PHONY : source/GameFeatures/Jogar/Fase1/carrega_unidades.s

# target to generate assembly for a file
source/GameFeatures/Jogar/Fase1/carrega_unidades.cpp.s:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/GameFeatures/Jogar/Fase1/carrega_unidades.cpp.s
.PHONY : source/GameFeatures/Jogar/Fase1/carrega_unidades.cpp.s

source/GameFeatures/Jogar/Fase1/carregar_fase1.o: source/GameFeatures/Jogar/Fase1/carregar_fase1.cpp.o

.PHONY : source/GameFeatures/Jogar/Fase1/carregar_fase1.o

# target to build an object file
source/GameFeatures/Jogar/Fase1/carregar_fase1.cpp.o:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/GameFeatures/Jogar/Fase1/carregar_fase1.cpp.o
.PHONY : source/GameFeatures/Jogar/Fase1/carregar_fase1.cpp.o

source/GameFeatures/Jogar/Fase1/carregar_fase1.i: source/GameFeatures/Jogar/Fase1/carregar_fase1.cpp.i

.PHONY : source/GameFeatures/Jogar/Fase1/carregar_fase1.i

# target to preprocess a source file
source/GameFeatures/Jogar/Fase1/carregar_fase1.cpp.i:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/GameFeatures/Jogar/Fase1/carregar_fase1.cpp.i
.PHONY : source/GameFeatures/Jogar/Fase1/carregar_fase1.cpp.i

source/GameFeatures/Jogar/Fase1/carregar_fase1.s: source/GameFeatures/Jogar/Fase1/carregar_fase1.cpp.s

.PHONY : source/GameFeatures/Jogar/Fase1/carregar_fase1.s

# target to generate assembly for a file
source/GameFeatures/Jogar/Fase1/carregar_fase1.cpp.s:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/GameFeatures/Jogar/Fase1/carregar_fase1.cpp.s
.PHONY : source/GameFeatures/Jogar/Fase1/carregar_fase1.cpp.s

source/GameFeatures/Jogar/Fase1/evolucao.o: source/GameFeatures/Jogar/Fase1/evolucao.cpp.o

.PHONY : source/GameFeatures/Jogar/Fase1/evolucao.o

# target to build an object file
source/GameFeatures/Jogar/Fase1/evolucao.cpp.o:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/GameFeatures/Jogar/Fase1/evolucao.cpp.o
.PHONY : source/GameFeatures/Jogar/Fase1/evolucao.cpp.o

source/GameFeatures/Jogar/Fase1/evolucao.i: source/GameFeatures/Jogar/Fase1/evolucao.cpp.i

.PHONY : source/GameFeatures/Jogar/Fase1/evolucao.i

# target to preprocess a source file
source/GameFeatures/Jogar/Fase1/evolucao.cpp.i:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/GameFeatures/Jogar/Fase1/evolucao.cpp.i
.PHONY : source/GameFeatures/Jogar/Fase1/evolucao.cpp.i

source/GameFeatures/Jogar/Fase1/evolucao.s: source/GameFeatures/Jogar/Fase1/evolucao.cpp.s

.PHONY : source/GameFeatures/Jogar/Fase1/evolucao.s

# target to generate assembly for a file
source/GameFeatures/Jogar/Fase1/evolucao.cpp.s:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/GameFeatures/Jogar/Fase1/evolucao.cpp.s
.PHONY : source/GameFeatures/Jogar/Fase1/evolucao.cpp.s

source/GameFeatures/Jogar/Fase1/fase1.o: source/GameFeatures/Jogar/Fase1/fase1.cpp.o

.PHONY : source/GameFeatures/Jogar/Fase1/fase1.o

# target to build an object file
source/GameFeatures/Jogar/Fase1/fase1.cpp.o:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/GameFeatures/Jogar/Fase1/fase1.cpp.o
.PHONY : source/GameFeatures/Jogar/Fase1/fase1.cpp.o

source/GameFeatures/Jogar/Fase1/fase1.i: source/GameFeatures/Jogar/Fase1/fase1.cpp.i

.PHONY : source/GameFeatures/Jogar/Fase1/fase1.i

# target to preprocess a source file
source/GameFeatures/Jogar/Fase1/fase1.cpp.i:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/GameFeatures/Jogar/Fase1/fase1.cpp.i
.PHONY : source/GameFeatures/Jogar/Fase1/fase1.cpp.i

source/GameFeatures/Jogar/Fase1/fase1.s: source/GameFeatures/Jogar/Fase1/fase1.cpp.s

.PHONY : source/GameFeatures/Jogar/Fase1/fase1.s

# target to generate assembly for a file
source/GameFeatures/Jogar/Fase1/fase1.cpp.s:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/GameFeatures/Jogar/Fase1/fase1.cpp.s
.PHONY : source/GameFeatures/Jogar/Fase1/fase1.cpp.s

source/GameFeatures/Jogar/Fase1/verifica_hexagono.o: source/GameFeatures/Jogar/Fase1/verifica_hexagono.cpp.o

.PHONY : source/GameFeatures/Jogar/Fase1/verifica_hexagono.o

# target to build an object file
source/GameFeatures/Jogar/Fase1/verifica_hexagono.cpp.o:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/GameFeatures/Jogar/Fase1/verifica_hexagono.cpp.o
.PHONY : source/GameFeatures/Jogar/Fase1/verifica_hexagono.cpp.o

source/GameFeatures/Jogar/Fase1/verifica_hexagono.i: source/GameFeatures/Jogar/Fase1/verifica_hexagono.cpp.i

.PHONY : source/GameFeatures/Jogar/Fase1/verifica_hexagono.i

# target to preprocess a source file
source/GameFeatures/Jogar/Fase1/verifica_hexagono.cpp.i:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/GameFeatures/Jogar/Fase1/verifica_hexagono.cpp.i
.PHONY : source/GameFeatures/Jogar/Fase1/verifica_hexagono.cpp.i

source/GameFeatures/Jogar/Fase1/verifica_hexagono.s: source/GameFeatures/Jogar/Fase1/verifica_hexagono.cpp.s

.PHONY : source/GameFeatures/Jogar/Fase1/verifica_hexagono.s

# target to generate assembly for a file
source/GameFeatures/Jogar/Fase1/verifica_hexagono.cpp.s:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/GameFeatures/Jogar/Fase1/verifica_hexagono.cpp.s
.PHONY : source/GameFeatures/Jogar/Fase1/verifica_hexagono.cpp.s

source/GameFeatures/Jogar/Fase2/carrega_unidades2.o: source/GameFeatures/Jogar/Fase2/carrega_unidades2.cpp.o

.PHONY : source/GameFeatures/Jogar/Fase2/carrega_unidades2.o

# target to build an object file
source/GameFeatures/Jogar/Fase2/carrega_unidades2.cpp.o:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/GameFeatures/Jogar/Fase2/carrega_unidades2.cpp.o
.PHONY : source/GameFeatures/Jogar/Fase2/carrega_unidades2.cpp.o

source/GameFeatures/Jogar/Fase2/carrega_unidades2.i: source/GameFeatures/Jogar/Fase2/carrega_unidades2.cpp.i

.PHONY : source/GameFeatures/Jogar/Fase2/carrega_unidades2.i

# target to preprocess a source file
source/GameFeatures/Jogar/Fase2/carrega_unidades2.cpp.i:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/GameFeatures/Jogar/Fase2/carrega_unidades2.cpp.i
.PHONY : source/GameFeatures/Jogar/Fase2/carrega_unidades2.cpp.i

source/GameFeatures/Jogar/Fase2/carrega_unidades2.s: source/GameFeatures/Jogar/Fase2/carrega_unidades2.cpp.s

.PHONY : source/GameFeatures/Jogar/Fase2/carrega_unidades2.s

# target to generate assembly for a file
source/GameFeatures/Jogar/Fase2/carrega_unidades2.cpp.s:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/GameFeatures/Jogar/Fase2/carrega_unidades2.cpp.s
.PHONY : source/GameFeatures/Jogar/Fase2/carrega_unidades2.cpp.s

source/GameFeatures/Jogar/Fase2/carregar_fase2.o: source/GameFeatures/Jogar/Fase2/carregar_fase2.cpp.o

.PHONY : source/GameFeatures/Jogar/Fase2/carregar_fase2.o

# target to build an object file
source/GameFeatures/Jogar/Fase2/carregar_fase2.cpp.o:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/GameFeatures/Jogar/Fase2/carregar_fase2.cpp.o
.PHONY : source/GameFeatures/Jogar/Fase2/carregar_fase2.cpp.o

source/GameFeatures/Jogar/Fase2/carregar_fase2.i: source/GameFeatures/Jogar/Fase2/carregar_fase2.cpp.i

.PHONY : source/GameFeatures/Jogar/Fase2/carregar_fase2.i

# target to preprocess a source file
source/GameFeatures/Jogar/Fase2/carregar_fase2.cpp.i:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/GameFeatures/Jogar/Fase2/carregar_fase2.cpp.i
.PHONY : source/GameFeatures/Jogar/Fase2/carregar_fase2.cpp.i

source/GameFeatures/Jogar/Fase2/carregar_fase2.s: source/GameFeatures/Jogar/Fase2/carregar_fase2.cpp.s

.PHONY : source/GameFeatures/Jogar/Fase2/carregar_fase2.s

# target to generate assembly for a file
source/GameFeatures/Jogar/Fase2/carregar_fase2.cpp.s:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/GameFeatures/Jogar/Fase2/carregar_fase2.cpp.s
.PHONY : source/GameFeatures/Jogar/Fase2/carregar_fase2.cpp.s

source/GameFeatures/Jogar/Fase2/fase2.o: source/GameFeatures/Jogar/Fase2/fase2.cpp.o

.PHONY : source/GameFeatures/Jogar/Fase2/fase2.o

# target to build an object file
source/GameFeatures/Jogar/Fase2/fase2.cpp.o:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/GameFeatures/Jogar/Fase2/fase2.cpp.o
.PHONY : source/GameFeatures/Jogar/Fase2/fase2.cpp.o

source/GameFeatures/Jogar/Fase2/fase2.i: source/GameFeatures/Jogar/Fase2/fase2.cpp.i

.PHONY : source/GameFeatures/Jogar/Fase2/fase2.i

# target to preprocess a source file
source/GameFeatures/Jogar/Fase2/fase2.cpp.i:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/GameFeatures/Jogar/Fase2/fase2.cpp.i
.PHONY : source/GameFeatures/Jogar/Fase2/fase2.cpp.i

source/GameFeatures/Jogar/Fase2/fase2.s: source/GameFeatures/Jogar/Fase2/fase2.cpp.s

.PHONY : source/GameFeatures/Jogar/Fase2/fase2.s

# target to generate assembly for a file
source/GameFeatures/Jogar/Fase2/fase2.cpp.s:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/GameFeatures/Jogar/Fase2/fase2.cpp.s
.PHONY : source/GameFeatures/Jogar/Fase2/fase2.cpp.s

source/GameFeatures/Jogar/Fase3/carrega_unidades3.o: source/GameFeatures/Jogar/Fase3/carrega_unidades3.cpp.o

.PHONY : source/GameFeatures/Jogar/Fase3/carrega_unidades3.o

# target to build an object file
source/GameFeatures/Jogar/Fase3/carrega_unidades3.cpp.o:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/GameFeatures/Jogar/Fase3/carrega_unidades3.cpp.o
.PHONY : source/GameFeatures/Jogar/Fase3/carrega_unidades3.cpp.o

source/GameFeatures/Jogar/Fase3/carrega_unidades3.i: source/GameFeatures/Jogar/Fase3/carrega_unidades3.cpp.i

.PHONY : source/GameFeatures/Jogar/Fase3/carrega_unidades3.i

# target to preprocess a source file
source/GameFeatures/Jogar/Fase3/carrega_unidades3.cpp.i:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/GameFeatures/Jogar/Fase3/carrega_unidades3.cpp.i
.PHONY : source/GameFeatures/Jogar/Fase3/carrega_unidades3.cpp.i

source/GameFeatures/Jogar/Fase3/carrega_unidades3.s: source/GameFeatures/Jogar/Fase3/carrega_unidades3.cpp.s

.PHONY : source/GameFeatures/Jogar/Fase3/carrega_unidades3.s

# target to generate assembly for a file
source/GameFeatures/Jogar/Fase3/carrega_unidades3.cpp.s:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/GameFeatures/Jogar/Fase3/carrega_unidades3.cpp.s
.PHONY : source/GameFeatures/Jogar/Fase3/carrega_unidades3.cpp.s

source/GameFeatures/Jogar/Fase3/carregar_fase3.o: source/GameFeatures/Jogar/Fase3/carregar_fase3.cpp.o

.PHONY : source/GameFeatures/Jogar/Fase3/carregar_fase3.o

# target to build an object file
source/GameFeatures/Jogar/Fase3/carregar_fase3.cpp.o:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/GameFeatures/Jogar/Fase3/carregar_fase3.cpp.o
.PHONY : source/GameFeatures/Jogar/Fase3/carregar_fase3.cpp.o

source/GameFeatures/Jogar/Fase3/carregar_fase3.i: source/GameFeatures/Jogar/Fase3/carregar_fase3.cpp.i

.PHONY : source/GameFeatures/Jogar/Fase3/carregar_fase3.i

# target to preprocess a source file
source/GameFeatures/Jogar/Fase3/carregar_fase3.cpp.i:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/GameFeatures/Jogar/Fase3/carregar_fase3.cpp.i
.PHONY : source/GameFeatures/Jogar/Fase3/carregar_fase3.cpp.i

source/GameFeatures/Jogar/Fase3/carregar_fase3.s: source/GameFeatures/Jogar/Fase3/carregar_fase3.cpp.s

.PHONY : source/GameFeatures/Jogar/Fase3/carregar_fase3.s

# target to generate assembly for a file
source/GameFeatures/Jogar/Fase3/carregar_fase3.cpp.s:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/GameFeatures/Jogar/Fase3/carregar_fase3.cpp.s
.PHONY : source/GameFeatures/Jogar/Fase3/carregar_fase3.cpp.s

source/GameFeatures/Jogar/Fase3/fase3.o: source/GameFeatures/Jogar/Fase3/fase3.cpp.o

.PHONY : source/GameFeatures/Jogar/Fase3/fase3.o

# target to build an object file
source/GameFeatures/Jogar/Fase3/fase3.cpp.o:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/GameFeatures/Jogar/Fase3/fase3.cpp.o
.PHONY : source/GameFeatures/Jogar/Fase3/fase3.cpp.o

source/GameFeatures/Jogar/Fase3/fase3.i: source/GameFeatures/Jogar/Fase3/fase3.cpp.i

.PHONY : source/GameFeatures/Jogar/Fase3/fase3.i

# target to preprocess a source file
source/GameFeatures/Jogar/Fase3/fase3.cpp.i:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/GameFeatures/Jogar/Fase3/fase3.cpp.i
.PHONY : source/GameFeatures/Jogar/Fase3/fase3.cpp.i

source/GameFeatures/Jogar/Fase3/fase3.s: source/GameFeatures/Jogar/Fase3/fase3.cpp.s

.PHONY : source/GameFeatures/Jogar/Fase3/fase3.s

# target to generate assembly for a file
source/GameFeatures/Jogar/Fase3/fase3.cpp.s:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/GameFeatures/Jogar/Fase3/fase3.cpp.s
.PHONY : source/GameFeatures/Jogar/Fase3/fase3.cpp.s

source/GameFeatures/Jogar/Fase4/carrega_unidades4.o: source/GameFeatures/Jogar/Fase4/carrega_unidades4.cpp.o

.PHONY : source/GameFeatures/Jogar/Fase4/carrega_unidades4.o

# target to build an object file
source/GameFeatures/Jogar/Fase4/carrega_unidades4.cpp.o:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/GameFeatures/Jogar/Fase4/carrega_unidades4.cpp.o
.PHONY : source/GameFeatures/Jogar/Fase4/carrega_unidades4.cpp.o

source/GameFeatures/Jogar/Fase4/carrega_unidades4.i: source/GameFeatures/Jogar/Fase4/carrega_unidades4.cpp.i

.PHONY : source/GameFeatures/Jogar/Fase4/carrega_unidades4.i

# target to preprocess a source file
source/GameFeatures/Jogar/Fase4/carrega_unidades4.cpp.i:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/GameFeatures/Jogar/Fase4/carrega_unidades4.cpp.i
.PHONY : source/GameFeatures/Jogar/Fase4/carrega_unidades4.cpp.i

source/GameFeatures/Jogar/Fase4/carrega_unidades4.s: source/GameFeatures/Jogar/Fase4/carrega_unidades4.cpp.s

.PHONY : source/GameFeatures/Jogar/Fase4/carrega_unidades4.s

# target to generate assembly for a file
source/GameFeatures/Jogar/Fase4/carrega_unidades4.cpp.s:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/GameFeatures/Jogar/Fase4/carrega_unidades4.cpp.s
.PHONY : source/GameFeatures/Jogar/Fase4/carrega_unidades4.cpp.s

source/GameFeatures/Jogar/Fase4/carregar_fase4.o: source/GameFeatures/Jogar/Fase4/carregar_fase4.cpp.o

.PHONY : source/GameFeatures/Jogar/Fase4/carregar_fase4.o

# target to build an object file
source/GameFeatures/Jogar/Fase4/carregar_fase4.cpp.o:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/GameFeatures/Jogar/Fase4/carregar_fase4.cpp.o
.PHONY : source/GameFeatures/Jogar/Fase4/carregar_fase4.cpp.o

source/GameFeatures/Jogar/Fase4/carregar_fase4.i: source/GameFeatures/Jogar/Fase4/carregar_fase4.cpp.i

.PHONY : source/GameFeatures/Jogar/Fase4/carregar_fase4.i

# target to preprocess a source file
source/GameFeatures/Jogar/Fase4/carregar_fase4.cpp.i:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/GameFeatures/Jogar/Fase4/carregar_fase4.cpp.i
.PHONY : source/GameFeatures/Jogar/Fase4/carregar_fase4.cpp.i

source/GameFeatures/Jogar/Fase4/carregar_fase4.s: source/GameFeatures/Jogar/Fase4/carregar_fase4.cpp.s

.PHONY : source/GameFeatures/Jogar/Fase4/carregar_fase4.s

# target to generate assembly for a file
source/GameFeatures/Jogar/Fase4/carregar_fase4.cpp.s:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/GameFeatures/Jogar/Fase4/carregar_fase4.cpp.s
.PHONY : source/GameFeatures/Jogar/Fase4/carregar_fase4.cpp.s

source/GameFeatures/Jogar/Fase4/fase4.o: source/GameFeatures/Jogar/Fase4/fase4.cpp.o

.PHONY : source/GameFeatures/Jogar/Fase4/fase4.o

# target to build an object file
source/GameFeatures/Jogar/Fase4/fase4.cpp.o:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/GameFeatures/Jogar/Fase4/fase4.cpp.o
.PHONY : source/GameFeatures/Jogar/Fase4/fase4.cpp.o

source/GameFeatures/Jogar/Fase4/fase4.i: source/GameFeatures/Jogar/Fase4/fase4.cpp.i

.PHONY : source/GameFeatures/Jogar/Fase4/fase4.i

# target to preprocess a source file
source/GameFeatures/Jogar/Fase4/fase4.cpp.i:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/GameFeatures/Jogar/Fase4/fase4.cpp.i
.PHONY : source/GameFeatures/Jogar/Fase4/fase4.cpp.i

source/GameFeatures/Jogar/Fase4/fase4.s: source/GameFeatures/Jogar/Fase4/fase4.cpp.s

.PHONY : source/GameFeatures/Jogar/Fase4/fase4.s

# target to generate assembly for a file
source/GameFeatures/Jogar/Fase4/fase4.cpp.s:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/GameFeatures/Jogar/Fase4/fase4.cpp.s
.PHONY : source/GameFeatures/Jogar/Fase4/fase4.cpp.s

source/GameFeatures/Jogar/Fase5/carregar_fase5.o: source/GameFeatures/Jogar/Fase5/carregar_fase5.cpp.o

.PHONY : source/GameFeatures/Jogar/Fase5/carregar_fase5.o

# target to build an object file
source/GameFeatures/Jogar/Fase5/carregar_fase5.cpp.o:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/GameFeatures/Jogar/Fase5/carregar_fase5.cpp.o
.PHONY : source/GameFeatures/Jogar/Fase5/carregar_fase5.cpp.o

source/GameFeatures/Jogar/Fase5/carregar_fase5.i: source/GameFeatures/Jogar/Fase5/carregar_fase5.cpp.i

.PHONY : source/GameFeatures/Jogar/Fase5/carregar_fase5.i

# target to preprocess a source file
source/GameFeatures/Jogar/Fase5/carregar_fase5.cpp.i:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/GameFeatures/Jogar/Fase5/carregar_fase5.cpp.i
.PHONY : source/GameFeatures/Jogar/Fase5/carregar_fase5.cpp.i

source/GameFeatures/Jogar/Fase5/carregar_fase5.s: source/GameFeatures/Jogar/Fase5/carregar_fase5.cpp.s

.PHONY : source/GameFeatures/Jogar/Fase5/carregar_fase5.s

# target to generate assembly for a file
source/GameFeatures/Jogar/Fase5/carregar_fase5.cpp.s:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/GameFeatures/Jogar/Fase5/carregar_fase5.cpp.s
.PHONY : source/GameFeatures/Jogar/Fase5/carregar_fase5.cpp.s

source/GameFeatures/Jogar/Fase5/fase5.o: source/GameFeatures/Jogar/Fase5/fase5.cpp.o

.PHONY : source/GameFeatures/Jogar/Fase5/fase5.o

# target to build an object file
source/GameFeatures/Jogar/Fase5/fase5.cpp.o:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/GameFeatures/Jogar/Fase5/fase5.cpp.o
.PHONY : source/GameFeatures/Jogar/Fase5/fase5.cpp.o

source/GameFeatures/Jogar/Fase5/fase5.i: source/GameFeatures/Jogar/Fase5/fase5.cpp.i

.PHONY : source/GameFeatures/Jogar/Fase5/fase5.i

# target to preprocess a source file
source/GameFeatures/Jogar/Fase5/fase5.cpp.i:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/GameFeatures/Jogar/Fase5/fase5.cpp.i
.PHONY : source/GameFeatures/Jogar/Fase5/fase5.cpp.i

source/GameFeatures/Jogar/Fase5/fase5.s: source/GameFeatures/Jogar/Fase5/fase5.cpp.s

.PHONY : source/GameFeatures/Jogar/Fase5/fase5.s

# target to generate assembly for a file
source/GameFeatures/Jogar/Fase5/fase5.cpp.s:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/GameFeatures/Jogar/Fase5/fase5.cpp.s
.PHONY : source/GameFeatures/Jogar/Fase5/fase5.cpp.s

source/GameFeatures/Jogar/coleta_recursos.o: source/GameFeatures/Jogar/coleta_recursos.cpp.o

.PHONY : source/GameFeatures/Jogar/coleta_recursos.o

# target to build an object file
source/GameFeatures/Jogar/coleta_recursos.cpp.o:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/GameFeatures/Jogar/coleta_recursos.cpp.o
.PHONY : source/GameFeatures/Jogar/coleta_recursos.cpp.o

source/GameFeatures/Jogar/coleta_recursos.i: source/GameFeatures/Jogar/coleta_recursos.cpp.i

.PHONY : source/GameFeatures/Jogar/coleta_recursos.i

# target to preprocess a source file
source/GameFeatures/Jogar/coleta_recursos.cpp.i:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/GameFeatures/Jogar/coleta_recursos.cpp.i
.PHONY : source/GameFeatures/Jogar/coleta_recursos.cpp.i

source/GameFeatures/Jogar/coleta_recursos.s: source/GameFeatures/Jogar/coleta_recursos.cpp.s

.PHONY : source/GameFeatures/Jogar/coleta_recursos.s

# target to generate assembly for a file
source/GameFeatures/Jogar/coleta_recursos.cpp.s:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/GameFeatures/Jogar/coleta_recursos.cpp.s
.PHONY : source/GameFeatures/Jogar/coleta_recursos.cpp.s

source/GameFeatures/Jogar/jogar.o: source/GameFeatures/Jogar/jogar.cpp.o

.PHONY : source/GameFeatures/Jogar/jogar.o

# target to build an object file
source/GameFeatures/Jogar/jogar.cpp.o:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/GameFeatures/Jogar/jogar.cpp.o
.PHONY : source/GameFeatures/Jogar/jogar.cpp.o

source/GameFeatures/Jogar/jogar.i: source/GameFeatures/Jogar/jogar.cpp.i

.PHONY : source/GameFeatures/Jogar/jogar.i

# target to preprocess a source file
source/GameFeatures/Jogar/jogar.cpp.i:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/GameFeatures/Jogar/jogar.cpp.i
.PHONY : source/GameFeatures/Jogar/jogar.cpp.i

source/GameFeatures/Jogar/jogar.s: source/GameFeatures/Jogar/jogar.cpp.s

.PHONY : source/GameFeatures/Jogar/jogar.s

# target to generate assembly for a file
source/GameFeatures/Jogar/jogar.cpp.s:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/GameFeatures/Jogar/jogar.cpp.s
.PHONY : source/GameFeatures/Jogar/jogar.cpp.s

source/GameFeatures/Jogar/venceu_perdeu.o: source/GameFeatures/Jogar/venceu_perdeu.cpp.o

.PHONY : source/GameFeatures/Jogar/venceu_perdeu.o

# target to build an object file
source/GameFeatures/Jogar/venceu_perdeu.cpp.o:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/GameFeatures/Jogar/venceu_perdeu.cpp.o
.PHONY : source/GameFeatures/Jogar/venceu_perdeu.cpp.o

source/GameFeatures/Jogar/venceu_perdeu.i: source/GameFeatures/Jogar/venceu_perdeu.cpp.i

.PHONY : source/GameFeatures/Jogar/venceu_perdeu.i

# target to preprocess a source file
source/GameFeatures/Jogar/venceu_perdeu.cpp.i:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/GameFeatures/Jogar/venceu_perdeu.cpp.i
.PHONY : source/GameFeatures/Jogar/venceu_perdeu.cpp.i

source/GameFeatures/Jogar/venceu_perdeu.s: source/GameFeatures/Jogar/venceu_perdeu.cpp.s

.PHONY : source/GameFeatures/Jogar/venceu_perdeu.s

# target to generate assembly for a file
source/GameFeatures/Jogar/venceu_perdeu.cpp.s:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/GameFeatures/Jogar/venceu_perdeu.cpp.s
.PHONY : source/GameFeatures/Jogar/venceu_perdeu.cpp.s

source/GameFeatures/Menu/menu.o: source/GameFeatures/Menu/menu.cpp.o

.PHONY : source/GameFeatures/Menu/menu.o

# target to build an object file
source/GameFeatures/Menu/menu.cpp.o:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/GameFeatures/Menu/menu.cpp.o
.PHONY : source/GameFeatures/Menu/menu.cpp.o

source/GameFeatures/Menu/menu.i: source/GameFeatures/Menu/menu.cpp.i

.PHONY : source/GameFeatures/Menu/menu.i

# target to preprocess a source file
source/GameFeatures/Menu/menu.cpp.i:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/GameFeatures/Menu/menu.cpp.i
.PHONY : source/GameFeatures/Menu/menu.cpp.i

source/GameFeatures/Menu/menu.s: source/GameFeatures/Menu/menu.cpp.s

.PHONY : source/GameFeatures/Menu/menu.s

# target to generate assembly for a file
source/GameFeatures/Menu/menu.cpp.s:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/GameFeatures/Menu/menu.cpp.s
.PHONY : source/GameFeatures/Menu/menu.cpp.s

source/GameFeatures/Opcoes/opcoes.o: source/GameFeatures/Opcoes/opcoes.cpp.o

.PHONY : source/GameFeatures/Opcoes/opcoes.o

# target to build an object file
source/GameFeatures/Opcoes/opcoes.cpp.o:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/GameFeatures/Opcoes/opcoes.cpp.o
.PHONY : source/GameFeatures/Opcoes/opcoes.cpp.o

source/GameFeatures/Opcoes/opcoes.i: source/GameFeatures/Opcoes/opcoes.cpp.i

.PHONY : source/GameFeatures/Opcoes/opcoes.i

# target to preprocess a source file
source/GameFeatures/Opcoes/opcoes.cpp.i:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/GameFeatures/Opcoes/opcoes.cpp.i
.PHONY : source/GameFeatures/Opcoes/opcoes.cpp.i

source/GameFeatures/Opcoes/opcoes.s: source/GameFeatures/Opcoes/opcoes.cpp.s

.PHONY : source/GameFeatures/Opcoes/opcoes.s

# target to generate assembly for a file
source/GameFeatures/Opcoes/opcoes.cpp.s:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/GameFeatures/Opcoes/opcoes.cpp.s
.PHONY : source/GameFeatures/Opcoes/opcoes.cpp.s

source/GameFeatures/blit_tela.o: source/GameFeatures/blit_tela.cpp.o

.PHONY : source/GameFeatures/blit_tela.o

# target to build an object file
source/GameFeatures/blit_tela.cpp.o:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/GameFeatures/blit_tela.cpp.o
.PHONY : source/GameFeatures/blit_tela.cpp.o

source/GameFeatures/blit_tela.i: source/GameFeatures/blit_tela.cpp.i

.PHONY : source/GameFeatures/blit_tela.i

# target to preprocess a source file
source/GameFeatures/blit_tela.cpp.i:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/GameFeatures/blit_tela.cpp.i
.PHONY : source/GameFeatures/blit_tela.cpp.i

source/GameFeatures/blit_tela.s: source/GameFeatures/blit_tela.cpp.s

.PHONY : source/GameFeatures/blit_tela.s

# target to generate assembly for a file
source/GameFeatures/blit_tela.cpp.s:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/GameFeatures/blit_tela.cpp.s
.PHONY : source/GameFeatures/blit_tela.cpp.s

source/PostWar.o: source/PostWar.cpp.o

.PHONY : source/PostWar.o

# target to build an object file
source/PostWar.cpp.o:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/PostWar.cpp.o
.PHONY : source/PostWar.cpp.o

source/PostWar.i: source/PostWar.cpp.i

.PHONY : source/PostWar.i

# target to preprocess a source file
source/PostWar.cpp.i:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/PostWar.cpp.i
.PHONY : source/PostWar.cpp.i

source/PostWar.s: source/PostWar.cpp.s

.PHONY : source/PostWar.s

# target to generate assembly for a file
source/PostWar.cpp.s:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/PostWar.cpp.s
.PHONY : source/PostWar.cpp.s

source/features/Collision/collision.o: source/features/Collision/collision.cpp.o

.PHONY : source/features/Collision/collision.o

# target to build an object file
source/features/Collision/collision.cpp.o:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/features/Collision/collision.cpp.o
.PHONY : source/features/Collision/collision.cpp.o

source/features/Collision/collision.i: source/features/Collision/collision.cpp.i

.PHONY : source/features/Collision/collision.i

# target to preprocess a source file
source/features/Collision/collision.cpp.i:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/features/Collision/collision.cpp.i
.PHONY : source/features/Collision/collision.cpp.i

source/features/Collision/collision.s: source/features/Collision/collision.cpp.s

.PHONY : source/features/Collision/collision.s

# target to generate assembly for a file
source/features/Collision/collision.cpp.s:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/features/Collision/collision.cpp.s
.PHONY : source/features/Collision/collision.cpp.s

source/features/Input/input.o: source/features/Input/input.cpp.o

.PHONY : source/features/Input/input.o

# target to build an object file
source/features/Input/input.cpp.o:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/features/Input/input.cpp.o
.PHONY : source/features/Input/input.cpp.o

source/features/Input/input.i: source/features/Input/input.cpp.i

.PHONY : source/features/Input/input.i

# target to preprocess a source file
source/features/Input/input.cpp.i:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/features/Input/input.cpp.i
.PHONY : source/features/Input/input.cpp.i

source/features/Input/input.s: source/features/Input/input.cpp.s

.PHONY : source/features/Input/input.s

# target to generate assembly for a file
source/features/Input/input.cpp.s:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/features/Input/input.cpp.s
.PHONY : source/features/Input/input.cpp.s

source/features/MiscTasks/audio.o: source/features/MiscTasks/audio.cpp.o

.PHONY : source/features/MiscTasks/audio.o

# target to build an object file
source/features/MiscTasks/audio.cpp.o:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/features/MiscTasks/audio.cpp.o
.PHONY : source/features/MiscTasks/audio.cpp.o

source/features/MiscTasks/audio.i: source/features/MiscTasks/audio.cpp.i

.PHONY : source/features/MiscTasks/audio.i

# target to preprocess a source file
source/features/MiscTasks/audio.cpp.i:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/features/MiscTasks/audio.cpp.i
.PHONY : source/features/MiscTasks/audio.cpp.i

source/features/MiscTasks/audio.s: source/features/MiscTasks/audio.cpp.s

.PHONY : source/features/MiscTasks/audio.s

# target to generate assembly for a file
source/features/MiscTasks/audio.cpp.s:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/features/MiscTasks/audio.cpp.s
.PHONY : source/features/MiscTasks/audio.cpp.s

source/features/MiscTasks/fontes.o: source/features/MiscTasks/fontes.cpp.o

.PHONY : source/features/MiscTasks/fontes.o

# target to build an object file
source/features/MiscTasks/fontes.cpp.o:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/features/MiscTasks/fontes.cpp.o
.PHONY : source/features/MiscTasks/fontes.cpp.o

source/features/MiscTasks/fontes.i: source/features/MiscTasks/fontes.cpp.i

.PHONY : source/features/MiscTasks/fontes.i

# target to preprocess a source file
source/features/MiscTasks/fontes.cpp.i:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/features/MiscTasks/fontes.cpp.i
.PHONY : source/features/MiscTasks/fontes.cpp.i

source/features/MiscTasks/fontes.s: source/features/MiscTasks/fontes.cpp.s

.PHONY : source/features/MiscTasks/fontes.s

# target to generate assembly for a file
source/features/MiscTasks/fontes.cpp.s:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/features/MiscTasks/fontes.cpp.s
.PHONY : source/features/MiscTasks/fontes.cpp.s

source/features/MiscTasks/misktasks.o: source/features/MiscTasks/misktasks.cpp.o

.PHONY : source/features/MiscTasks/misktasks.o

# target to build an object file
source/features/MiscTasks/misktasks.cpp.o:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/features/MiscTasks/misktasks.cpp.o
.PHONY : source/features/MiscTasks/misktasks.cpp.o

source/features/MiscTasks/misktasks.i: source/features/MiscTasks/misktasks.cpp.i

.PHONY : source/features/MiscTasks/misktasks.i

# target to preprocess a source file
source/features/MiscTasks/misktasks.cpp.i:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/features/MiscTasks/misktasks.cpp.i
.PHONY : source/features/MiscTasks/misktasks.cpp.i

source/features/MiscTasks/misktasks.s: source/features/MiscTasks/misktasks.cpp.s

.PHONY : source/features/MiscTasks/misktasks.s

# target to generate assembly for a file
source/features/MiscTasks/misktasks.cpp.s:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/features/MiscTasks/misktasks.cpp.s
.PHONY : source/features/MiscTasks/misktasks.cpp.s

source/features/Network/client.o: source/features/Network/client.cpp.o

.PHONY : source/features/Network/client.o

# target to build an object file
source/features/Network/client.cpp.o:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/features/Network/client.cpp.o
.PHONY : source/features/Network/client.cpp.o

source/features/Network/client.i: source/features/Network/client.cpp.i

.PHONY : source/features/Network/client.i

# target to preprocess a source file
source/features/Network/client.cpp.i:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/features/Network/client.cpp.i
.PHONY : source/features/Network/client.cpp.i

source/features/Network/client.s: source/features/Network/client.cpp.s

.PHONY : source/features/Network/client.s

# target to generate assembly for a file
source/features/Network/client.cpp.s:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/features/Network/client.cpp.s
.PHONY : source/features/Network/client.cpp.s

source/features/Network/network.o: source/features/Network/network.cpp.o

.PHONY : source/features/Network/network.o

# target to build an object file
source/features/Network/network.cpp.o:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/features/Network/network.cpp.o
.PHONY : source/features/Network/network.cpp.o

source/features/Network/network.i: source/features/Network/network.cpp.i

.PHONY : source/features/Network/network.i

# target to preprocess a source file
source/features/Network/network.cpp.i:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/features/Network/network.cpp.i
.PHONY : source/features/Network/network.cpp.i

source/features/Network/network.s: source/features/Network/network.cpp.s

.PHONY : source/features/Network/network.s

# target to generate assembly for a file
source/features/Network/network.cpp.s:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/features/Network/network.cpp.s
.PHONY : source/features/Network/network.cpp.s

source/features/Network/server.o: source/features/Network/server.cpp.o

.PHONY : source/features/Network/server.o

# target to build an object file
source/features/Network/server.cpp.o:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/features/Network/server.cpp.o
.PHONY : source/features/Network/server.cpp.o

source/features/Network/server.i: source/features/Network/server.cpp.i

.PHONY : source/features/Network/server.i

# target to preprocess a source file
source/features/Network/server.cpp.i:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/features/Network/server.cpp.i
.PHONY : source/features/Network/server.cpp.i

source/features/Network/server.s: source/features/Network/server.cpp.s

.PHONY : source/features/Network/server.s

# target to generate assembly for a file
source/features/Network/server.cpp.s:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/features/Network/server.cpp.s
.PHONY : source/features/Network/server.cpp.s

source/features/RenderWorld/draw.o: source/features/RenderWorld/draw.cpp.o

.PHONY : source/features/RenderWorld/draw.o

# target to build an object file
source/features/RenderWorld/draw.cpp.o:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/features/RenderWorld/draw.cpp.o
.PHONY : source/features/RenderWorld/draw.cpp.o

source/features/RenderWorld/draw.i: source/features/RenderWorld/draw.cpp.i

.PHONY : source/features/RenderWorld/draw.i

# target to preprocess a source file
source/features/RenderWorld/draw.cpp.i:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/features/RenderWorld/draw.cpp.i
.PHONY : source/features/RenderWorld/draw.cpp.i

source/features/RenderWorld/draw.s: source/features/RenderWorld/draw.cpp.s

.PHONY : source/features/RenderWorld/draw.s

# target to generate assembly for a file
source/features/RenderWorld/draw.cpp.s:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/features/RenderWorld/draw.cpp.s
.PHONY : source/features/RenderWorld/draw.cpp.s

source/features/RenderWorld/load_image.o: source/features/RenderWorld/load_image.cpp.o

.PHONY : source/features/RenderWorld/load_image.o

# target to build an object file
source/features/RenderWorld/load_image.cpp.o:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/features/RenderWorld/load_image.cpp.o
.PHONY : source/features/RenderWorld/load_image.cpp.o

source/features/RenderWorld/load_image.i: source/features/RenderWorld/load_image.cpp.i

.PHONY : source/features/RenderWorld/load_image.i

# target to preprocess a source file
source/features/RenderWorld/load_image.cpp.i:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/features/RenderWorld/load_image.cpp.i
.PHONY : source/features/RenderWorld/load_image.cpp.i

source/features/RenderWorld/load_image.s: source/features/RenderWorld/load_image.cpp.s

.PHONY : source/features/RenderWorld/load_image.s

# target to generate assembly for a file
source/features/RenderWorld/load_image.cpp.s:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/features/RenderWorld/load_image.cpp.s
.PHONY : source/features/RenderWorld/load_image.cpp.s

source/features/RenderWorld/renderworld.o: source/features/RenderWorld/renderworld.cpp.o

.PHONY : source/features/RenderWorld/renderworld.o

# target to build an object file
source/features/RenderWorld/renderworld.cpp.o:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/features/RenderWorld/renderworld.cpp.o
.PHONY : source/features/RenderWorld/renderworld.cpp.o

source/features/RenderWorld/renderworld.i: source/features/RenderWorld/renderworld.cpp.i

.PHONY : source/features/RenderWorld/renderworld.i

# target to preprocess a source file
source/features/RenderWorld/renderworld.cpp.i:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/features/RenderWorld/renderworld.cpp.i
.PHONY : source/features/RenderWorld/renderworld.cpp.i

source/features/RenderWorld/renderworld.s: source/features/RenderWorld/renderworld.cpp.s

.PHONY : source/features/RenderWorld/renderworld.s

# target to generate assembly for a file
source/features/RenderWorld/renderworld.cpp.s:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/features/RenderWorld/renderworld.cpp.s
.PHONY : source/features/RenderWorld/renderworld.cpp.s

source/features/RenderWorld/video.o: source/features/RenderWorld/video.cpp.o

.PHONY : source/features/RenderWorld/video.o

# target to build an object file
source/features/RenderWorld/video.cpp.o:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/features/RenderWorld/video.cpp.o
.PHONY : source/features/RenderWorld/video.cpp.o

source/features/RenderWorld/video.i: source/features/RenderWorld/video.cpp.i

.PHONY : source/features/RenderWorld/video.i

# target to preprocess a source file
source/features/RenderWorld/video.cpp.i:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/features/RenderWorld/video.cpp.i
.PHONY : source/features/RenderWorld/video.cpp.i

source/features/RenderWorld/video.s: source/features/RenderWorld/video.cpp.s

.PHONY : source/features/RenderWorld/video.s

# target to generate assembly for a file
source/features/RenderWorld/video.cpp.s:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/features/RenderWorld/video.cpp.s
.PHONY : source/features/RenderWorld/video.cpp.s

source/features/SimulatedWorld/simulated.o: source/features/SimulatedWorld/simulated.cpp.o

.PHONY : source/features/SimulatedWorld/simulated.o

# target to build an object file
source/features/SimulatedWorld/simulated.cpp.o:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/features/SimulatedWorld/simulated.cpp.o
.PHONY : source/features/SimulatedWorld/simulated.cpp.o

source/features/SimulatedWorld/simulated.i: source/features/SimulatedWorld/simulated.cpp.i

.PHONY : source/features/SimulatedWorld/simulated.i

# target to preprocess a source file
source/features/SimulatedWorld/simulated.cpp.i:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/features/SimulatedWorld/simulated.cpp.i
.PHONY : source/features/SimulatedWorld/simulated.cpp.i

source/features/SimulatedWorld/simulated.s: source/features/SimulatedWorld/simulated.cpp.s

.PHONY : source/features/SimulatedWorld/simulated.s

# target to generate assembly for a file
source/features/SimulatedWorld/simulated.cpp.s:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/features/SimulatedWorld/simulated.cpp.s
.PHONY : source/features/SimulatedWorld/simulated.cpp.s

source/features/UpdateObjects/ataque_unidade.o: source/features/UpdateObjects/ataque_unidade.cpp.o

.PHONY : source/features/UpdateObjects/ataque_unidade.o

# target to build an object file
source/features/UpdateObjects/ataque_unidade.cpp.o:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/features/UpdateObjects/ataque_unidade.cpp.o
.PHONY : source/features/UpdateObjects/ataque_unidade.cpp.o

source/features/UpdateObjects/ataque_unidade.i: source/features/UpdateObjects/ataque_unidade.cpp.i

.PHONY : source/features/UpdateObjects/ataque_unidade.i

# target to preprocess a source file
source/features/UpdateObjects/ataque_unidade.cpp.i:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/features/UpdateObjects/ataque_unidade.cpp.i
.PHONY : source/features/UpdateObjects/ataque_unidade.cpp.i

source/features/UpdateObjects/ataque_unidade.s: source/features/UpdateObjects/ataque_unidade.cpp.s

.PHONY : source/features/UpdateObjects/ataque_unidade.s

# target to generate assembly for a file
source/features/UpdateObjects/ataque_unidade.cpp.s:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/features/UpdateObjects/ataque_unidade.cpp.s
.PHONY : source/features/UpdateObjects/ataque_unidade.cpp.s

source/features/UpdateObjects/condicao_fim_do_jogo.o: source/features/UpdateObjects/condicao_fim_do_jogo.cpp.o

.PHONY : source/features/UpdateObjects/condicao_fim_do_jogo.o

# target to build an object file
source/features/UpdateObjects/condicao_fim_do_jogo.cpp.o:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/features/UpdateObjects/condicao_fim_do_jogo.cpp.o
.PHONY : source/features/UpdateObjects/condicao_fim_do_jogo.cpp.o

source/features/UpdateObjects/condicao_fim_do_jogo.i: source/features/UpdateObjects/condicao_fim_do_jogo.cpp.i

.PHONY : source/features/UpdateObjects/condicao_fim_do_jogo.i

# target to preprocess a source file
source/features/UpdateObjects/condicao_fim_do_jogo.cpp.i:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/features/UpdateObjects/condicao_fim_do_jogo.cpp.i
.PHONY : source/features/UpdateObjects/condicao_fim_do_jogo.cpp.i

source/features/UpdateObjects/condicao_fim_do_jogo.s: source/features/UpdateObjects/condicao_fim_do_jogo.cpp.s

.PHONY : source/features/UpdateObjects/condicao_fim_do_jogo.s

# target to generate assembly for a file
source/features/UpdateObjects/condicao_fim_do_jogo.cpp.s:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/features/UpdateObjects/condicao_fim_do_jogo.cpp.s
.PHONY : source/features/UpdateObjects/condicao_fim_do_jogo.cpp.s

source/features/UpdateObjects/dano_ataque.o: source/features/UpdateObjects/dano_ataque.cpp.o

.PHONY : source/features/UpdateObjects/dano_ataque.o

# target to build an object file
source/features/UpdateObjects/dano_ataque.cpp.o:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/features/UpdateObjects/dano_ataque.cpp.o
.PHONY : source/features/UpdateObjects/dano_ataque.cpp.o

source/features/UpdateObjects/dano_ataque.i: source/features/UpdateObjects/dano_ataque.cpp.i

.PHONY : source/features/UpdateObjects/dano_ataque.i

# target to preprocess a source file
source/features/UpdateObjects/dano_ataque.cpp.i:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/features/UpdateObjects/dano_ataque.cpp.i
.PHONY : source/features/UpdateObjects/dano_ataque.cpp.i

source/features/UpdateObjects/dano_ataque.s: source/features/UpdateObjects/dano_ataque.cpp.s

.PHONY : source/features/UpdateObjects/dano_ataque.s

# target to generate assembly for a file
source/features/UpdateObjects/dano_ataque.cpp.s:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/features/UpdateObjects/dano_ataque.cpp.s
.PHONY : source/features/UpdateObjects/dano_ataque.cpp.s

source/features/UpdateObjects/mover_unidade.o: source/features/UpdateObjects/mover_unidade.cpp.o

.PHONY : source/features/UpdateObjects/mover_unidade.o

# target to build an object file
source/features/UpdateObjects/mover_unidade.cpp.o:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/features/UpdateObjects/mover_unidade.cpp.o
.PHONY : source/features/UpdateObjects/mover_unidade.cpp.o

source/features/UpdateObjects/mover_unidade.i: source/features/UpdateObjects/mover_unidade.cpp.i

.PHONY : source/features/UpdateObjects/mover_unidade.i

# target to preprocess a source file
source/features/UpdateObjects/mover_unidade.cpp.i:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/features/UpdateObjects/mover_unidade.cpp.i
.PHONY : source/features/UpdateObjects/mover_unidade.cpp.i

source/features/UpdateObjects/mover_unidade.s: source/features/UpdateObjects/mover_unidade.cpp.s

.PHONY : source/features/UpdateObjects/mover_unidade.s

# target to generate assembly for a file
source/features/UpdateObjects/mover_unidade.cpp.s:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/features/UpdateObjects/mover_unidade.cpp.s
.PHONY : source/features/UpdateObjects/mover_unidade.cpp.s

source/features/UpdateObjects/updateobjects.o: source/features/UpdateObjects/updateobjects.cpp.o

.PHONY : source/features/UpdateObjects/updateobjects.o

# target to build an object file
source/features/UpdateObjects/updateobjects.cpp.o:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/features/UpdateObjects/updateobjects.cpp.o
.PHONY : source/features/UpdateObjects/updateobjects.cpp.o

source/features/UpdateObjects/updateobjects.i: source/features/UpdateObjects/updateobjects.cpp.i

.PHONY : source/features/UpdateObjects/updateobjects.i

# target to preprocess a source file
source/features/UpdateObjects/updateobjects.cpp.i:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/features/UpdateObjects/updateobjects.cpp.i
.PHONY : source/features/UpdateObjects/updateobjects.cpp.i

source/features/UpdateObjects/updateobjects.s: source/features/UpdateObjects/updateobjects.cpp.s

.PHONY : source/features/UpdateObjects/updateobjects.s

# target to generate assembly for a file
source/features/UpdateObjects/updateobjects.cpp.s:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/features/UpdateObjects/updateobjects.cpp.s
.PHONY : source/features/UpdateObjects/updateobjects.cpp.s

source/features/UpdateTime/update_time.o: source/features/UpdateTime/update_time.cpp.o

.PHONY : source/features/UpdateTime/update_time.o

# target to build an object file
source/features/UpdateTime/update_time.cpp.o:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/features/UpdateTime/update_time.cpp.o
.PHONY : source/features/UpdateTime/update_time.cpp.o

source/features/UpdateTime/update_time.i: source/features/UpdateTime/update_time.cpp.i

.PHONY : source/features/UpdateTime/update_time.i

# target to preprocess a source file
source/features/UpdateTime/update_time.cpp.i:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/features/UpdateTime/update_time.cpp.i
.PHONY : source/features/UpdateTime/update_time.cpp.i

source/features/UpdateTime/update_time.s: source/features/UpdateTime/update_time.cpp.s

.PHONY : source/features/UpdateTime/update_time.s

# target to generate assembly for a file
source/features/UpdateTime/update_time.cpp.s:
	$(MAKE) -f CMakeFiles/postwar.dir/build.make CMakeFiles/postwar.dir/source/features/UpdateTime/update_time.cpp.s
.PHONY : source/features/UpdateTime/update_time.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... postwar"
	@echo "... package"
	@echo "... package_source"
	@echo "... edit_cache"
	@echo "... source/GameFeatures/Creditos/creditos.o"
	@echo "... source/GameFeatures/Creditos/creditos.i"
	@echo "... source/GameFeatures/Creditos/creditos.s"
	@echo "... source/GameFeatures/Jogar/Fase1/carrega_unidades.o"
	@echo "... source/GameFeatures/Jogar/Fase1/carrega_unidades.i"
	@echo "... source/GameFeatures/Jogar/Fase1/carrega_unidades.s"
	@echo "... source/GameFeatures/Jogar/Fase1/carregar_fase1.o"
	@echo "... source/GameFeatures/Jogar/Fase1/carregar_fase1.i"
	@echo "... source/GameFeatures/Jogar/Fase1/carregar_fase1.s"
	@echo "... source/GameFeatures/Jogar/Fase1/evolucao.o"
	@echo "... source/GameFeatures/Jogar/Fase1/evolucao.i"
	@echo "... source/GameFeatures/Jogar/Fase1/evolucao.s"
	@echo "... source/GameFeatures/Jogar/Fase1/fase1.o"
	@echo "... source/GameFeatures/Jogar/Fase1/fase1.i"
	@echo "... source/GameFeatures/Jogar/Fase1/fase1.s"
	@echo "... source/GameFeatures/Jogar/Fase1/verifica_hexagono.o"
	@echo "... source/GameFeatures/Jogar/Fase1/verifica_hexagono.i"
	@echo "... source/GameFeatures/Jogar/Fase1/verifica_hexagono.s"
	@echo "... source/GameFeatures/Jogar/Fase2/carrega_unidades2.o"
	@echo "... source/GameFeatures/Jogar/Fase2/carrega_unidades2.i"
	@echo "... source/GameFeatures/Jogar/Fase2/carrega_unidades2.s"
	@echo "... source/GameFeatures/Jogar/Fase2/carregar_fase2.o"
	@echo "... source/GameFeatures/Jogar/Fase2/carregar_fase2.i"
	@echo "... source/GameFeatures/Jogar/Fase2/carregar_fase2.s"
	@echo "... source/GameFeatures/Jogar/Fase2/fase2.o"
	@echo "... source/GameFeatures/Jogar/Fase2/fase2.i"
	@echo "... source/GameFeatures/Jogar/Fase2/fase2.s"
	@echo "... source/GameFeatures/Jogar/Fase3/carrega_unidades3.o"
	@echo "... source/GameFeatures/Jogar/Fase3/carrega_unidades3.i"
	@echo "... source/GameFeatures/Jogar/Fase3/carrega_unidades3.s"
	@echo "... source/GameFeatures/Jogar/Fase3/carregar_fase3.o"
	@echo "... source/GameFeatures/Jogar/Fase3/carregar_fase3.i"
	@echo "... source/GameFeatures/Jogar/Fase3/carregar_fase3.s"
	@echo "... source/GameFeatures/Jogar/Fase3/fase3.o"
	@echo "... source/GameFeatures/Jogar/Fase3/fase3.i"
	@echo "... source/GameFeatures/Jogar/Fase3/fase3.s"
	@echo "... source/GameFeatures/Jogar/Fase4/carrega_unidades4.o"
	@echo "... source/GameFeatures/Jogar/Fase4/carrega_unidades4.i"
	@echo "... source/GameFeatures/Jogar/Fase4/carrega_unidades4.s"
	@echo "... source/GameFeatures/Jogar/Fase4/carregar_fase4.o"
	@echo "... source/GameFeatures/Jogar/Fase4/carregar_fase4.i"
	@echo "... source/GameFeatures/Jogar/Fase4/carregar_fase4.s"
	@echo "... source/GameFeatures/Jogar/Fase4/fase4.o"
	@echo "... source/GameFeatures/Jogar/Fase4/fase4.i"
	@echo "... source/GameFeatures/Jogar/Fase4/fase4.s"
	@echo "... source/GameFeatures/Jogar/Fase5/carregar_fase5.o"
	@echo "... source/GameFeatures/Jogar/Fase5/carregar_fase5.i"
	@echo "... source/GameFeatures/Jogar/Fase5/carregar_fase5.s"
	@echo "... source/GameFeatures/Jogar/Fase5/fase5.o"
	@echo "... source/GameFeatures/Jogar/Fase5/fase5.i"
	@echo "... source/GameFeatures/Jogar/Fase5/fase5.s"
	@echo "... source/GameFeatures/Jogar/coleta_recursos.o"
	@echo "... source/GameFeatures/Jogar/coleta_recursos.i"
	@echo "... source/GameFeatures/Jogar/coleta_recursos.s"
	@echo "... source/GameFeatures/Jogar/jogar.o"
	@echo "... source/GameFeatures/Jogar/jogar.i"
	@echo "... source/GameFeatures/Jogar/jogar.s"
	@echo "... source/GameFeatures/Jogar/venceu_perdeu.o"
	@echo "... source/GameFeatures/Jogar/venceu_perdeu.i"
	@echo "... source/GameFeatures/Jogar/venceu_perdeu.s"
	@echo "... source/GameFeatures/Menu/menu.o"
	@echo "... source/GameFeatures/Menu/menu.i"
	@echo "... source/GameFeatures/Menu/menu.s"
	@echo "... source/GameFeatures/Opcoes/opcoes.o"
	@echo "... source/GameFeatures/Opcoes/opcoes.i"
	@echo "... source/GameFeatures/Opcoes/opcoes.s"
	@echo "... source/GameFeatures/blit_tela.o"
	@echo "... source/GameFeatures/blit_tela.i"
	@echo "... source/GameFeatures/blit_tela.s"
	@echo "... source/PostWar.o"
	@echo "... source/PostWar.i"
	@echo "... source/PostWar.s"
	@echo "... source/features/Collision/collision.o"
	@echo "... source/features/Collision/collision.i"
	@echo "... source/features/Collision/collision.s"
	@echo "... source/features/Input/input.o"
	@echo "... source/features/Input/input.i"
	@echo "... source/features/Input/input.s"
	@echo "... source/features/MiscTasks/audio.o"
	@echo "... source/features/MiscTasks/audio.i"
	@echo "... source/features/MiscTasks/audio.s"
	@echo "... source/features/MiscTasks/fontes.o"
	@echo "... source/features/MiscTasks/fontes.i"
	@echo "... source/features/MiscTasks/fontes.s"
	@echo "... source/features/MiscTasks/misktasks.o"
	@echo "... source/features/MiscTasks/misktasks.i"
	@echo "... source/features/MiscTasks/misktasks.s"
	@echo "... source/features/Network/client.o"
	@echo "... source/features/Network/client.i"
	@echo "... source/features/Network/client.s"
	@echo "... source/features/Network/network.o"
	@echo "... source/features/Network/network.i"
	@echo "... source/features/Network/network.s"
	@echo "... source/features/Network/server.o"
	@echo "... source/features/Network/server.i"
	@echo "... source/features/Network/server.s"
	@echo "... source/features/RenderWorld/draw.o"
	@echo "... source/features/RenderWorld/draw.i"
	@echo "... source/features/RenderWorld/draw.s"
	@echo "... source/features/RenderWorld/load_image.o"
	@echo "... source/features/RenderWorld/load_image.i"
	@echo "... source/features/RenderWorld/load_image.s"
	@echo "... source/features/RenderWorld/renderworld.o"
	@echo "... source/features/RenderWorld/renderworld.i"
	@echo "... source/features/RenderWorld/renderworld.s"
	@echo "... source/features/RenderWorld/video.o"
	@echo "... source/features/RenderWorld/video.i"
	@echo "... source/features/RenderWorld/video.s"
	@echo "... source/features/SimulatedWorld/simulated.o"
	@echo "... source/features/SimulatedWorld/simulated.i"
	@echo "... source/features/SimulatedWorld/simulated.s"
	@echo "... source/features/UpdateObjects/ataque_unidade.o"
	@echo "... source/features/UpdateObjects/ataque_unidade.i"
	@echo "... source/features/UpdateObjects/ataque_unidade.s"
	@echo "... source/features/UpdateObjects/condicao_fim_do_jogo.o"
	@echo "... source/features/UpdateObjects/condicao_fim_do_jogo.i"
	@echo "... source/features/UpdateObjects/condicao_fim_do_jogo.s"
	@echo "... source/features/UpdateObjects/dano_ataque.o"
	@echo "... source/features/UpdateObjects/dano_ataque.i"
	@echo "... source/features/UpdateObjects/dano_ataque.s"
	@echo "... source/features/UpdateObjects/mover_unidade.o"
	@echo "... source/features/UpdateObjects/mover_unidade.i"
	@echo "... source/features/UpdateObjects/mover_unidade.s"
	@echo "... source/features/UpdateObjects/updateobjects.o"
	@echo "... source/features/UpdateObjects/updateobjects.i"
	@echo "... source/features/UpdateObjects/updateobjects.s"
	@echo "... source/features/UpdateTime/update_time.o"
	@echo "... source/features/UpdateTime/update_time.i"
	@echo "... source/features/UpdateTime/update_time.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

